Добавлены ассоциации
VadikVadik/test_guru pull request #4
Opened 2021-08-28 14:23 UTC by VadikVadik

2021-08-28 21:03 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :created_tests, class_name: 'Test'
а где миграция на добавление этого поля?

2021-08-29 11:43 UTC, VadikVadik commented on app/models/user.rb
> +  has_many :created_tests, class_name: 'Test'
Какого этого?

2021-08-29 18:47 UTC, BubuntuClu requested changes

2021-08-29 18:47 UTC, BubuntuClu commented on db/migrate/20210829173629_add_author_to_test.rb
> +    add_column :tests, :author, :integer
сделай добавление колонки с внешним ключем и индексом за одну миграцию. используй `add_reference`

2021-08-29 18:47 UTC, BubuntuClu requested changes

2021-08-29 18:47 UTC, BubuntuClu commented on db/schema.rb
> +    t.integer "author"
название колонки не правильное, у тебя ведь тут не объект, а id пользователя

2021-08-30 06:57 UTC, BubuntuClu requested changes

2021-08-30 06:57 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
у тебя нет такого внешнего ключа. ты ведь другое имя добавил для колонки)

2021-08-30 06:57 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :created_tests, class_name: 'Test'
эта ассоциация работает? мне кажется, надо внешний ключ добавить

2021-08-30 06:57 UTC, BubuntuClu requested changes

2021-08-30 06:57 UTC, BubuntuClu commented on db/migrate/20210829173629_add_author_to_test.rb
> +class AddAuthorToTest < ActiveRecord::Migration[6.1]
эту миграцию надо удалить

2021-08-30 06:57 UTC, BubuntuClu commented on db/migrate/20210829180223_add_author_test_association.rb
> +class AddAuthorTestAssociation < ActiveRecord::Migration[6.1]
эту миграцию надо удалить

2021-08-30 16:58 UTC, BubuntuClu requested changes

2021-08-30 16:58 UTC, BubuntuClu commented on db/migrate/20210829193038_add_test_user_reference.rb
> +    add_reference(:users, :created_tests, foreign_key: {to_table: :tests})
это зачем? это лишнее. у тебя связь выше используется для реализации этого задания

2021-08-30 16:58 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :created_tests, class_name: 'Test', foreign_key: 'created_tests_id'
как это должно работать? опиши процесс как у тебя создается запись в это поле и как планируется ее использовать?

2021-08-31 16:18 UTC, merged